/*
 * Copyright (C) 2012-2016. TomTom International BV (http://tomtom.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __DEP_CHECKER__CONSTANTS_H
#define __DEP_CHECKER__CONSTANTS_H

#define CMAKEFILE_TAG "GENERATED BY DEPENDENCYCHECKER"

#define CURRENT_VERSION "2"
#define VERSION_FILE "cpp-dependencies-version.txt"

#define COLOR_CYCLIC_DEPENDENCY "orange"
#define COLOR_PUBLIC_DEPENDENCY "blue"
#define COLOR_PRIVATE_DEPENDENCY "lightblue"
#define CURSES_CYCLIC_DEPENDENCY "[33m"
#define CURSES_PUBLIC_DEPENDENCY "[34m"
#define CURSES_PRIVATE_DEPENDENCY "[36m"
#define CURSES_RESET_COLOR "[39;49m"


#endif

